const forecastAdvice = {
    "body-sun": {
        "zodiac-aries": { 
            en: "A week of dynamic movement and fiery momentum unfolds before you. Your inner flame burns with exceptional intensity now, urging you to take bold action. Channel this passionate energy to clear long-standing obstacles that have blocked your path. This is your moment to ignite transformation and breathe vibrant new life into projects or relationships that have grown stagnant. The cosmos rewards courage and initiative during this powerful cycle.", 
            vn: "Một tuần đầy năng lượng bùng cháy và những bước tiến mạnh mẽ đang trải ra trước mắt bạn. Ngọn lửa nội tại của bạn đang rực sáng với cường độ phi thường, thôi thúc bạn hành động táo bạo. Hãy dẫn dắt nguồn năng lượng đam mê này để phá tan những rào cản lâu nay đã chặn đường bạn. Đây là thời khắc để bạn khơi dậy sự chuyển hóa, thổi hồn sống mãnh liệt vào những dự án hay mối quan hệ đã trì trệ quá lâu. Vũ trụ ban thưởng cho lòng dũng cảm và sự chủ động trong chu kỳ quyền năng này." 
        },
        "zodiac-taurus": { 
            en: "The celestial patterns reveal a grounding rhythm that beckons you to slow down and deepen your roots. This week calls for patient cultivation of your foundations—whether in career, relationships, or personal well-being. Growth may appear gradual, yet it is profoundly inevitable under the steady gaze of the stars. Tend to what truly matters with devotion, for the universe is building something enduring through your hands. Trust in the wisdom of organic development.", 
            vn: "Các tinh tú hiện ra nhịp điệu ổn định, mời gọi bạn chậm lại và đâm rễ sâu hơn vào nền tảng. Tuần này đòi hỏi sự kiên nhẫn vun trồng những nền móng của bạn—dù trong sự nghiệp, tình cảm hay sức khỏe tinh thần. Sự phát triển có vẻ chậm rãi, nhưng nó sâu sắc và tất yếu dưới ánh mắt bền bỉ của những vì sao. Hãy chăm sóc những gì thật sự quan trọng bằng cả tấm lòng, bởi vũ trụ đang xây dựng điều gì đó trường tồn qua đôi tay bạn. Hãy tin vào sự khôn ngoan của quá trình phát triển tự nhiên." 
        },
        "zodiac-gemini": { 
            en: "The air crackles with whispers of connection and intellectual possibility. Over the next seven days, the cosmic winds favor vibrant exchanges of ideas, meaningful conversations, and the weaving of fascinating new social threads. Your curiosity is a sacred gift right now—follow it fearlessly. Engage with diverse perspectives, share your insights generously, and allow your natural adaptability to create bridges between people and concepts. Communication becomes magic when wielded with awareness.", 
            vn: "Không khí rung động với những lời thầm thì của kết nối và khả năng trí tuệ vô tận. Trong bảy ngày tới, những cơn gió vũ trụ ưu ái cho sự trao đổi ý tưởng sôi nổi, những cuộc trò chuyện sâu sắc, và việc dệt nên những mạng lưới xã hội đầy thú vị. Sự tò mò của bạn là món quà thiêng liêng lúc này—hãy theo đuổi nó không sợ hãi. Tiếp xúc với những góc nhìn đa dạng, chia sẻ hiểu biết của bạn hào phóng, và để khả năng thích nghi tự nhiên tạo cầu nối giữa con người với nhau. Giao tiếp trở thành phép màu khi được sử dụng với tâm thức sáng suốt." 
        },
        "zodiac-cancer": { 
            en: "The cosmic tide pulls you inexorably toward the sanctuaries of home and heart. This week invites deep emotional honoring—allow yourself to feel fully, without judgment or resistance. As your feelings ebb and flow like moon-touched waters, they reveal hidden pearls of profound wisdom. Nurture yourself and your loved ones with tenderness. Create sacred space for vulnerability, for it is through emotional authenticity that you discover your greatest strength and deepest truths.", 
            vn: "Thủy triều vũ trụ kéo bạn về những thánh địa của tổ ấm và trái tim. Tuần này mời gọi bạn tôn vinh sâu sắc những cảm xúc—hãy cho phép mình cảm nhận trọn vẹn, không phán xét hay kháng cự. Khi những tâm tư của bạn dâng lên rồi lắng xuống như làn nước được mặt trăng chạm vào, chúng hé lộ những viên ngọc trí tuệ ẩn giấu. Hãy nuôi dưỡng bản thân và những người bạn yêu bằng sự dịu dàng. Tạo không gian thiêng cho sự mềm yếu, bởi chính qua sự chân thành trong cảm xúc mà bạn khám phá sức mạnh lớn nhất và chân lý sâu thẳm nhất." 
        },
        "zodiac-leo": { 
            en: "Radiance and creative brilliance are your destined companions this week. The universe turns its spotlight directly upon you, illuminating your unique gifts and inviting bold self-expression. Step confidently into center stage of your own magnificent life. Let your creative spirit dance freely with the stars, unafraid to shine at full intensity. This is your time to inspire others through authentic presence, to lead with heart, and to manifest the joy that is your birthright. Own your light unapologetically.", 
            vn: "Sự rạng rỡ và óc sáng tạo lấp lánh là những người bạn định mệnh của bạn tuần này. Vũ trụ hướng ánh đèn sân khấu thẳng vào bạn, chiếu sáng những tài năng độc đáo và mời gọi bạn thể hiện bản thân táo bạo. Hãy tự tin bước vào trung tâm sân khấu của chính cuộc đời tráng lệ mình. Để tinh thần sáng tạo nhảy múa tự do cùng những vì sao, không sợ tỏa sáng với cường độ tối đa. Đây là thời điểm để truyền cảm hứng cho người khác qua sự hiện diện chân thật, dẫn dắt bằng trái tim, và thể hiện niềm vui là quyền sinh ra của bạn. Hãy tự hào với ánh sáng của mình mà không xin lỗi." 
        },
        "zodiac-virgo": { 
            en: "Precision, discernment, and sacred alignment become your guiding stars this week. The universe extends its supportive hand to help you organize chaos into meaningful order, transforming scattered energies into purposeful action. Attend meticulously to details that others might overlook—therein lies your power. Your daily rituals and routines become vessels for divine grace when performed with mindful intention. Trust that perfection is found not in flawlessness but in conscious refinement and devoted service to what matters most.", 
            vn: "Sự chính xác, nhãn quan sắc bén và định hướng thiêng liêng trở thành ngôi sao dẫn đường của bạn tuần này. Vũ trụ đưa bàn tay hỗ trợ giúp bạn sắp xếp hỗn loạn thành trật tự có ý nghĩa, chuyển hóa năng lượng rời rạc thành hành động có mục đích. Hãy chú ý tỉ mỉ đến những chi tiết mà người khác có thể bỏ qua—ở đó chính là sức mạnh của bạn. Những nghi thức và thói quen hàng ngày trở thành bình chứa ân sủng thiêng khi được thực hiện với ý thức tỉnh táo. Hãy tin rằng sự hoàn hảo không nằm ở việc không tì vết, mà ở sự tinh luyện có ý thức và cống hiến hết mình cho những gì thật sự quan trọng." 
        },
        "zodiac-libra": { 
            en: "The cosmic scales seek perfect equilibrium through your consciousness this week. Balance becomes both your challenge and your gift—in relationships, decisions, and inner harmony. Seek the middle path with grace and diplomacy, yet do not sacrifice your truth for false peace. Your natural ability to see all perspectives serves as a beacon for others navigating difficult choices. Let beauty and fairness guide your interactions, and trust that authentic harmony emerges when opposing forces find respectful accord through your mediation.", 
            vn: "Cán cân vũ trụ tìm kiếm sự cân bằng hoàn hảo qua ý thức của bạn tuần này. Sự cân bằng trở thành cả thử thách lẫn món quà—trong các mối quan hệ, quyết định, và sự hài hòa nội tâm. Hãy tìm con đường trung dung với duyên dáng và ngoại giao, nhưng đừng hy sinh chân lý của mình cho hòa bình giả tạo. Khả năng tự nhiên nhìn thấy mọi góc độ của bạn trở thành ngọn hải đăng cho những ai đang băn khoăn với những lựa chọn khó khăn. Để vẻ đẹp và sự công bằng dẫn dắt các tương tác, và hãy tin rằng sự hài hòa chân thật xuất hiện khi những lực lượng đối lập tìm thấy sự tôn trọng qua sự hòa giải của bạn." 
        },
        "zodiac-scorpio": { 
            en: "Deep, alchemical transformation stirs in the hidden depths beneath your surface awareness. This week calls you to embrace the shadows without fear, for within darkness lies the raw power of rebirth and profound spiritual insight. What dies in you now makes space for something far more authentic to emerge. Trust the process of dissolution and regeneration. Your intensity is not a burden but a sacred gift—use it to penetrate illusions, transform pain into wisdom, and emerge with deeper understanding of life's mysteries.", 
            vn: "Sự chuyển hóa sâu sắc, mang tính thuật giả kim đang trỗi dậy trong những tầng sâu ẩn giấu dưới nhận thức bề mặt của bạn. Tuần này kêu gọi bạn đón nhận bóng tối mà không sợ hãi, bởi trong tăm tối ẩn chứa nguồn sức mạnh nguyên sơ của sự tái sinh và thấu thị tâm linh sâu sắc. Những gì chết đi trong bạn giờ đây tạo không gian cho điều gì đó chân thật hơn nhiều xuất hiện. Hãy tin vào quá trình tan rã và tái tạo. Cường độ của bạn không phải gánh nặng mà là món quà thiêng liêng—hãy dùng nó để thấu suốt ảo tưởng, chuyển hóa nỗi đau thành trí tuệ, và nổi lên với sự thấu hiểu sâu sắc hơn về những bí ẩn của cuộc đời." 
        },
        "zodiac-sagittarius": { 
            en: "The far horizon beckons to your wild, adventurous spirit with irresistible allure. This week expands your vision beyond familiar boundaries—geographically, philosophically, or spiritually. Trust in the journey and the wisdom gained through exploration. Your arrows of intention, when aimed with philosophical clarity and optimistic faith, will find their destined marks. Embrace the freedom to question, wander, and discover. Share the truth you find along the way, for your enthusiasm ignites hope in others seeking meaning.", 
            vn: "Đường chân trời xa xăm đang vẫy gọi linh hồn phiêu lưu hoang dã của bạn với sức hấp dẫn không thể cưỡng lại. Tuần này mở rộng tầm nhìn của bạn vượt qua những ranh giới quen thuộc—về địa lý, triết học, hay tâm linh. Hãy tin vào hành trình và trí tuệ thu được qua sự khám phá. Những mũi tên ý định của bạn, khi được nhắm với sự minh triết và niềm tin lạc quan, sẽ chạm tới những đích đến định mệnh. Hãy đón nhận sự tự do để đặt câu hỏi, lang thang, và khám phá. Chia sẻ chân lý bạn tìm thấy trên đường đi, bởi sự nhiệt tình của bạn thắp lên hy vọng trong những ai đang tìm kiếm ý nghĩa." 
        },
        "zodiac-capricorn": { 
            en: "Mastery through patient discipline defines your celestial path this week. The ancient stars align in support of your long-term ambitions and strategic vision. Build your dreams with the solidity of stone and the unwavering focus of mountain peaks reaching toward sky. This is not a time for shortcuts but for laying foundations that will endure through seasons and years. Your dedication to excellence and your capacity for sustained effort create lasting legacy. Trust in the power of incremental progress and consistent commitment.", 
            vn: "Sự làm chủ qua kỷ luật kiên nhẫn định nghĩa con đường thiên thể của bạn tuần này. Những vì sao cổ xưa sắp hàng ủng hộ những tham vọng dài hạn và tầm nhìn chiến lược của bạn. Hãy xây dựng ước mơ với độ vững chắc của đá và sự tập trung không lay chuyển của những đỉnh núi vươn lên trời cao. Đây không phải lúc để đi tắt mà là để đặt những nền móng sẽ trường tồn qua mùa và năm tháng. Sự cống hiến cho sự xuất sắc và khả năng nỗ lực bền bỉ của bạn tạo nên di sản lâu dài. Hãy tin vào sức mạnh của sự tiến bộ từng bước và cam kết kiên định." 
        },
        "zodiac-aquarius": { 
            en: "Visionary currents of innovation and collective awakening flow powerfully through your consciousness this week. The universe invites you to honor the utterly unique frequency of your soul's song and to share your revolutionary ideas with courage. Think beyond conventional boundaries—your gift to the world lies in seeing what others cannot yet imagine. Connect with like-minded spirits who share your passion for progress. Innovation thrives when you dare to be authentically different and trust your brilliant, unconventional insights.", 
            vn: "Những dòng chảy viễn cảnh của đổi mới và thức tỉnh tập thể đang chảy mạnh mẽ qua ý thức của bạn tuần này. Vũ trụ mời gọi bạn tôn vinh tần số hoàn toàn độc đáo của bài ca linh hồn và chia sẻ những ý tưởng cách mạng với lòng dũng cảm. Hãy suy nghĩ vượt qua những ranh giới thông thường—món quà của bạn cho thế giới nằm ở việc nhìn thấy những gì người khác chưa thể tưởng tượng. Kết nối với những tâm hồn đồng điệu chia sẻ đam mê tiến bộ. Sự đổi mới phát triển khi bạn dám trở nên khác biệt một cách chân thật và tin vào những thấu thị tuyệt vời, phi thường của mình." 
        },
        "zodiac-pisces": { 
            en: "The veil between visible and invisible realms grows gossamer-thin this week, opening portals to profound mystical understanding. Let intuition be your trusted compass as you navigate the misty, dreamlike landscapes of the soul's infinite waters. Your natural empathy and spiritual sensitivity reach heightened states—use them wisely to heal, create, and connect with the sacred. Trust the whispers that arrive in moments of stillness. Your imagination is a divine gift; honor it by bringing celestial visions into earthly form through art, compassion, or devoted service.", 
            vn: "Bức màn giữa cõi hữu hình và vô hình trở nên mỏng manh như tơ tuần này, mở những cánh cổng dẫn đến sự thấu hiểu huyền bí sâu sắc. Hãy để trực giác là la bàn đáng tin cậy khi bạn đi qua những cảnh sắc mơ màng, sương mù của vùng nước vô tận của tâm hồn. Khả năng đồng cảm tự nhiên và sự nhạy cảm tâm linh của bạn đạt trạng thái cao độ—hãy sử dụng chúng khôn ngoan để chữa lành, sáng tạo, và kết nối với cái thiêng. Tin vào những lời thì thầm đến trong những khoảnh khắc tĩnh lặng. Trí tưởng tượng của bạn là món quà thiêng liêng; hãy tôn vinh nó bằng việc mang những viễn cảnh thiên thượng xuống hình hài trần gian qua nghệ thuật, lòng trắc ẩn, hay sự phụng sự hết lòng." 
        }
    },
    "moon-cycle": {
        "waxing": { 
            en: "The lunar light grows stronger each night, mirroring the natural expansion that should occur within your own intentions and aspirations. This waxing phase is cosmically perfect for planting seeds of transformation and feeding them with consistent action, unwavering belief, and joyful anticipation. Whatever you wish to grow—relationships, projects, skills, or inner qualities—receives special blessing from the increasing moon. Harness this building energy deliberately and watch your carefully tended dreams begin to manifest in tangible form.", 
            vn: "Ánh trăng lớn dần mỗi đêm, phản chiếu sự mở rộng tự nhiên cần xảy ra trong chính những ý định và khát vọng của bạn. Pha trăng lên này hoàn hảo về mặt vũ trụ để gieo những hạt giống chuyển hóa và nuôi dưỡng chúng bằng hành động kiên định, niềm tin không lay chuyển, và sự mong đợi đầy niềm vui. Bất cứ điều gì bạn muốn phát triển—các mối quan hệ, dự án, kỹ năng, hay phẩm chất nội tâm—đều nhận được ơn phước đặc biệt từ mặt trăng đang tăng dần. Hãy khai thác nguồn năng lượng tích tụ này một cách có ý thức và theo dõi những ước mơ được chăm sóc cẩn thận bắt đầu hiện thực hóa dưới dạng hữu hình." 
        },
        "waning": { 
            en: "The universe exhales deeply, creating sacred space for necessary release and conscious letting go. As lunar light gradually diminishes, you are cosmically supported in shedding what no longer serves your highest evolution—old patterns, limiting beliefs, toxic connections, or accumulated burdens. This waning phase invites spiritual cleansing and energetic purification. Make space within yourself for future miracles by courageously releasing the past. Trust that what falls away creates room for something far more aligned with your authentic path to enter when the cycle renews.", 
            vn: "Vũ trụ thở ra sâu sắc, tạo không gian thiêng liêng cho sự buông bỏ cần thiết và thả lỏng có ý thức. Khi ánh trăng dần giảm, bạn được vũ trụ hỗ trợ trong việc rũ bỏ những gì không còn phục vụ sự tiến hóa cao nhất của mình—những khuôn mẫu cũ, niềm tin giới hạn, kết nối độc hại, hay những gánh nặng tích tụ. Pha trăng khuyết này mời gọi sự thanh lọc tâm linh và làm sạch năng lượng. Hãy tạo khoảng trống bên trong bản thân cho những điều kỳ diệu tương lai bằng cách dũng cảm buông bỏ quá khứ. Tin rằng những gì rơi đi tạo chỗ cho điều gì đó gắn kết hơn nhiều với con đường chân thật của bạn để bước vào khi chu kỳ được làm mới." 
        }
    }
};
